backup_tool_dir: /root/tools/backup # バックアップツールディレクトリ
backup_dir: /root/backup/jenkins # バックアップ先ディレクトリ
backup_limit_day: 31 # バックアップファイルの保存期間
cron_minute: "0"
cron_hour: "0"
cron_month: "*"
cron_weekday: "*"
